### ISSUE TITLE
Email list recruitment

### ISSUE THREAD

**Issue by AugustPaulsrud** [armada-ths/armada.nu#65]
### Task Description

Add the option for students to sign up to an email list to get notified of future host/ot/pg recruitments. [Eventro](https://app.eventro.se/o/armada) handles backend functionality, we are only implementing the user interface for it.

### Technical Details

- POST to https://app.eventro.se/api/v1/register-email-campaign-user when signing someone up. Complete API documentation can be found [here](https://app.eventro.se/api/v1/swagger#tag/email-campaigns/POST/api/v1/register-email-campaign-user/).

### Acceptance Criteria

- [ ] Email input field and signup button exists on the student recruitment page (and optionally in additional locations).
- [ ] Signup section is visible at all times; both during and outside of recruitment periods.
- [ ] It is clearly communicated what the user is signing up to.
- [ ] Confirmation message is shown after a user has signed up.
- [ ] Storybook coverage is sufficient (use own assessment of what new stories are needed, if any).

### Testing Notes

- Create a new email campaign in Eventro and try signing up through armada.nu.
- Send an email through the campaign and check that it is received.

**Comment by einhar1** [comment]
Here is Copilots proposed plan:

## Plan: SES recruitment opening notifications

Build a CMS-owned notification system in `ArmadaCMS` using AWS SES, with `armada.nu` only collecting emails and calling CMS APIs. This keeps secrets and delivery logic server-side, supports idempotent sends, and adds a safety buffer to prevent accidental blasts.

**Steps**
1. **Phase 1 — Data model & migration (blocking)**
   1. Add `RecruitmentNotificationSubscription` model (global list): normalized email, active/unsubscribed timestamps, metadata.
   2. Add `RecruitmentNotificationDispatch` model with unique `(subscription_id, recruitment_period_id)` to prevent duplicate sends.
   3. Add `RecruitmentNotificationJob` model with `send_after`, status, retry fields.
   4. Register new models in main.go `AutoMigrate`.

2. **Phase 2 — SES utility + config (depends on 1)**
   1. Add SES sender utility in utils (AWS SDK v2; fail-safe error returns, no panic).
   2. Add recruitment-open email template helper (HTML + text) including unsubscribe link.
   3. Add SES vars in .env.example (`SES_REGION`, `SES_FROM_ADDRESS`, AWS creds).
   4. Add startup validation behavior: email feature disabled with warning if SES config missing.

3. **Phase 3 — Public subscription endpoints (depends on 1, parallel with 2.2–2.4)**
   1. Add `POST /api/v1/recruitment-notifications/subscribe` (global signup).
   2. Add `GET /api/v1/recruitment-notifications/unsubscribe/{token}`.
   3. Use signed opaque unsubscribe tokens (no raw email in URLs).
   4. Make subscribe idempotent: existing active = no-op success; existing inactive = reactivate.
   5. Keep controller writes aligned with audit-helper policy.

4. **Phase 4 — Open transition + queue scheduling (depends on 1,2)**
   1. In `CreateRecruitmentPeriod` (`RecruitmentPeriodController`): if period is created already open, enqueue job with `send_after = now + 10m`.
   2. In `UpdateRecruitmentPeriod`: detect not-open → open transition and enqueue immediate job (`send_after = now`).
   3. If period closes before a due queued job executes, cancel/skip that job.
   4. Enforce one effective notification job per period transition to prevent duplicates.

5. **Phase 5 — Dispatcher worker (depends on 2,4)**
   1. Start lightweight worker from main.go that polls due jobs.
   2. On execution: re-check period still open, fetch active subscribers, send via SES, write dispatch rows, finalize job status.
   3. Add bounded retry/backoff for transient SES failures.
   4. Log sent/skipped/failed counts per job for observability.

6. **Phase 6 — `armada.nu` UI integration (depends on 3)**
   1. Add signup UI component to page.tsx (or colocated child component).
   2. Submit to CMS subscribe endpoint via `NEXT_PUBLIC_API_URL`.
   3. Show user-safe responses (success/already subscribed/invalid email/temporary failure).
   4. Keep existing feature-flag behavior (`STUDENT_RECRUITMENT_PAGE`) unchanged.

7. **Phase 7 — Abuse/compliance hardening (parallel with 6, before release)**
   1. Add subscribe endpoint rate limiting (IP + email).
   2. Add origin/captcha anti-abuse strategy.
   3. Include one-click unsubscribe in every message.
   4. Document SES identity setup (SPF/DKIM/DMARC).

8. **Phase 8 — Verification & rollout (depends on all)**
   1. Regenerate Swagger docs.
   2. Run backend checks: `go vet`, `golangci-lint`, `go test -race -count=1 Armada.`.
   3. Run staging E2E: subscribe → open transition send → unsubscribe respected.
   4. Validate safety rule: create already-open period, close/edit within 10 min, confirm no send.
   5. Deploy order: **ArmadaCMS first**, then `armada.nu`.

**Relevant files**
- main.go — models, routes, worker startup.
- RecruitmentPeriodController.go — enqueue logic on create/update.
- EventroRecruitmentController.go — current open/upcoming selection behavior reference.
- audit_write_helpers.go — write/audit transaction pattern.
- recruitment.go + new models in models.
- .env.example — SES env docs.
- page.tsx — signup placement.
- useRecruitment.ts — API base integration context.

**Verification**
1. Static/tests pass in CMS.
2. Swagger includes new endpoints.
3. DB uniqueness constraints prevent duplicate sends.
4. Manual staging flow verifies subscribe/send/unsubscribe behavior.
5. Safety-delay scenario verified.

**Decisions**
- Included: global next-opening list, single opt-in, automatic send on open, 10-minute delay only for created-already-open periods.
- Included: SES sending from CMS backend only (never browser/frontend direct).
- Excluded for v1: campaign editor/admin composer, advanced marketing flows.

**Comment by JuiceAndTheJoe** [comment]
Contacted Eventro about this - awaiting response

**Comment by JuiceAndTheJoe** [comment]
Still awaiting Eventro, Einar sent reminder

**Comment by einhar1** [comment]
<img width="1265" height="808" alt="Image" src="https://github.com/user-attachments/assets/74c52eee-e254-47bd-8b5d-21289ecd13d5" />

**Comment by einhar1** [comment]
Email lists are now a feature in Eventro. Use the following endpoint to sign someone up:

```
curl --request POST \
  'https://app.eventro.se/api/v1/register-email-campaign-user' \
  --header 'Content-Type: application/json' \
  --data '{
    "campaignId": "<id for campaign>",
    "email": "person@example.com",
    "name": "Ada Lovelace"
  }'
```
